apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: my-nginx-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-nginx-deployment
  template:
    metadata:
      labels:
        app: my-nginx-deployment
    spec:
      containers:
      - image: nginx:1.14
        imagePullPolicy: Always
        name: my-nginx-deployment
        ports:
        - containerPort: 80
          protocol: TCP
