apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  containers:
  - image: nginx:1.14
    imagePullPolicy: Always
    name: my-nginx
    ports:
    - containerPort: 80
      protocol: TCP
